<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Ad_ad_iframe</name>
   <tag></tag>
   <elementGuidId>d3c57e86-f1d9-4ec1-a407-8a64de92b024</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ad_iframe</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='ad_iframe']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>652b4f87-c2eb-45c8-bb06-9e177eead0bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Advertisement</value>
      <webElementGuid>dd14a6c0-de86-4e89-803a-1e5160481e77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ad_iframe</value>
      <webElementGuid>7ecb33ff-d91a-4898-b821-5d8747abbdbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ad_iframe</value>
      <webElementGuid>e9923be0-f2e0-4bb5-8149-a3891e20e555</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>57a98ee6-7c7b-40b9-8f47-0547e8a662bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>about:blank</value>
      <webElementGuid>347da01a-1a6b-4c8c-b747-f4aeb832abc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>99bb37f0-af21-46ff-92d5-0d85f1e0d4d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>486px</value>
      <webElementGuid>c4f0d3bb-5680-48d1-80b4-6bf3124247ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>194px</value>
      <webElementGuid>54cf2efd-419b-4cc6-9b04-4a857542a798</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ad_iframe&quot;)</value>
      <webElementGuid>1d2048c1-c694-4be0-ac0a-e4e7fcee74ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Guru99 Bank Home Page/iframe_concat(id(, , google_ads_iframe_2413_4c927e</value>
      <webElementGuid>949aba18-8342-4c4a-bc3c-d9c7ab299c41</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='ad_iframe']</value>
      <webElementGuid>ea5b5f82-7dc3-4310-902c-05eb749364d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='creative']/iframe</value>
      <webElementGuid>b4ea8c21-5560-42e8-84e1-97633b6bbc89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>a19b42e2-1287-4c24-8bc3-f83d006ac750</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'Advertisement' and @id = 'ad_iframe' and @name = 'ad_iframe' and @src = 'about:blank']</value>
      <webElementGuid>fa809ea7-3edf-465a-8acc-868075415281</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
